### PR TITLE
Add Hebrew translations to all strings

### PR DESCRIPTION
**Pull request by GabMic**
This pull request adds translations to all strings in the lang directory.

### CODE REVIEW

**Comment by range-of-motion** [comment]
Seems alright. Please just get rid of the `package-lock.json` 🙂

**Comment by range-of-motion** [comment]
Also, I think you should add `'he'` to the `locales` key in `config/app.php`. This way it becomes available in the UI's dropdown.

**Comment by GabMic** [comment]
> Also, I think you should add `'he'` to the `locales` key in `config/app.php`. This way it becomes available in the UI's dropdown.

Done :)

**Comment by range-of-motion** [comment]
Thanks. One last comment before I go ahead and merge this.

I'd like to keep the history clean, and therefor I'm asking you to amend the first commit, and remove the `package-lock.json` from there. Instead you've created a separate commit (the 3rd). 

Also, if you could–please rename the 2nd commit to be a bit more precise (something like "Added Hebrew to locales in app's configuration").

**Comment by range-of-motion** [comment]
I'm afraid this PR has gone stale. I'm going to close it, but if you feel like fixing it, don't hesitate to re-open it 🙂

**Pull request closed without merging**
