### PR TITLE
add missing php extension `ext-calendar`

### PR DESCRIPTION
**Pull request by maherelgamil**

### CODE REVIEW

**Comment by range-of-motion** [comment]
Can you show me where we use this extension?

**Comment by maherelgamil** [comment]
@range-of-motion at this line:
https://github.com/range-of-motion/budget/blob/master/app/Http/Controllers/DashboardController.php#L31

**Comment by range-of-motion** [comment]
Ah, this looks like a welcome change.

Could you add the line underneath the "php" requirement? That way we can group the PHP-related packages and keep `composer.json` organized.

**Comment by range-of-motion** [comment]
Since I haven't heard anything in a while I will go ahead and close this. But I will add `ext-calendar` to `composer.json`, I promise 😉

**Pull request closed without merging**
